owner: "55402625"
team: "16288796"
lastUpdatedBy: "55402625"
lastRevision: 1780583090000
name: Local
color: 0
values:
  - key: baseUrl
    value: http://localhost:4500
    enabled: true
  - key: jwtSecret
    value: YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=
    enabled: true
createdAt: 2026-06-04T14:17:23.000Z
updatedAt: 2026-06-04T14:24:50.000Z
